<?php

namespace App\Services\Reminders;

use App\Models\Car;
use App\Models\Reminder;
use App\Models\ServiceType;
use Illuminate\Support\Carbon;

/**
 * The product's heart: derives when each car should come back.
 *
 * Oil reminders are re-derived from the latest oil-change visit on every
 * visit save AND undo (single write path). Due date = whichever comes first:
 * the km interval at the car's own pace (average daily km across its visit
 * history, shop default for first-timers) or the time cap for the oil type.
 *
 * License reminders are generated by the daily `reminders:generate` command
 * within a lead window before each car's renewal month. Seasonal broadcasts
 * (winter/AC) are deliberately NOT auto-generated per car — they belong to
 * the announcements/campaign feature, not the call list.
 */
class ReminderEngine
{
    /** Oil type => interval. v1 constants; per-shop settings later. */
    public const INTERVALS = [
        'mineral' => ['km' => 4000, 'months' => 4],
        'synthetic' => ['km' => 10000, 'months' => 6],
    ];

    public const DEFAULT_OIL_TYPE = 'mineral';

    /** Generate a license reminder this many days before the renewal month. */
    public const LICENSE_LEAD_DAYS = 30;

    /** Sanity clamp for the learned pace — bad odometer entries happen. */
    private const MIN_DAILY_KM = 5.0;

    private const MAX_DAILY_KM = 500.0;

    // ── Oil ─────────────────────────────────────────────────────────────────

    /**
     * Upsert (or drop) the car's pending oil reminder from its latest
     * oil-change visit.
     */
    public function scheduleOilReminder(Car $car): void
    {
        $anchor = $car->latestOilVisit();
        $pending = $car->pendingOilReminder()->first();

        if ($anchor === null) {
            $pending?->delete();

            return;
        }

        $interval = self::INTERVALS[$anchor->oil_type ?? self::DEFAULT_OIL_TYPE] ?? self::INTERVALS[self::DEFAULT_OIL_TYPE];

        $dailyKm = $this->averageDailyKm($car) ?? (float) $car->shop->default_daily_km;
        $etaDays = (int) ceil($interval['km'] / max($dailyKm, 1.0));
        $capDays = (int) $anchor->visited_at->diffInDays($anchor->visited_at->copy()->addMonths($interval['months']));

        $attributes = [
            'visit_id' => $anchor->id,
            'label' => ServiceType::OIL_CHANGE,
            'due_km' => $anchor->km + $interval['km'],
            'due_date' => $anchor->visited_at->copy()->addDays(min($etaDays, $capDays))->toDateString(),
        ];

        if ($pending !== null) {
            $pending->update($attributes);

            return;
        }

        $reminder = $car->reminders()->make([...$attributes, 'type' => 'oil', 'status' => 'pending']);
        $reminder->shop_id = $car->shop_id;
        $reminder->save();
    }

    /**
     * The car's own pace, learned from its visit history: km delta between the
     * first and last visit over the days between them. Null (caller falls back
     * to the shop default) when there's no usable history.
     */
    public function averageDailyKm(Car $car): ?float
    {
        $first = $car->visits()->oldest('visited_at')->first();
        $last = $car->visits()->latest('visited_at')->first();

        if ($first === null || $last === null || $first->is($last)) {
            return null;
        }

        $days = (int) $first->visited_at->diffInDays($last->visited_at);
        $kmDelta = $last->km - $first->km;

        if ($days < 1 || $kmDelta <= 0) {
            return null;
        }

        return min(max($kmDelta / $days, self::MIN_DAILY_KM), self::MAX_DAILY_KM);
    }

    // ── License renewal (الترخيص) ───────────────────────────────────────────

    /**
     * Ensure every car with a known license month has a reminder for its next
     * renewal, created LICENSE_LEAD_DAYS ahead. Idempotent — safe to run daily;
     * next year's occurrence regenerates automatically.
     *
     * @return int number of reminders created
     */
    public function generateLicenseReminders(): int
    {
        $created = 0;
        $today = today();

        Car::query()
            ->whereNotNull('license_month')
            ->with(['reminders' => fn ($query) => $query
                ->where('type', 'license')
                ->where('due_date', '>=', $today->copy()->startOfMonth())])
            ->chunkById(200, function ($cars) use (&$created, $today) {
                foreach ($cars as $car) {
                    $due = $this->nextLicenseDue($car, $today);

                    if ((int) $today->diffInDays($due, false) > self::LICENSE_LEAD_DAYS) {
                        continue; // not in the lead window yet
                    }

                    if ($car->reminders->contains(fn (Reminder $r) => $r->due_date->isSameDay($due))) {
                        continue; // this occurrence already has a reminder (any status)
                    }

                    $reminder = $car->reminders()->make([
                        'type' => 'license',
                        'label' => "تجديد ترخيص · شهر {$car->license_month}/{$due->year}",
                        'due_date' => $due->toDateString(),
                        'status' => 'pending',
                    ]);
                    $reminder->shop_id = $car->shop_id;
                    $reminder->save();

                    $created++;
                }
            });

        return $created;
    }

    /**
     * First day of the car's next license month (this year, or next year once
     * the month has fully passed).
     */
    private function nextLicenseDue(Car $car, Carbon $today): Carbon
    {
        $due = Carbon::create($today->year, $car->license_month, 1);

        return $due->copy()->endOfMonth()->isBefore($today) ? $due->addYear() : $due;
    }
}
